[package]
name = "odoo-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.0"
env_logger = "0.10.0"
ropey = "1.5.0"
serde_json = "1.0.78"
tokio = { version = "1.17.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
serde = { version = "1.0", features = ["derive"] }
dashmap = "5.1.0"
log = "0.4.14"
im-rc = "15.0.0"
faststr = "0.2.11"
globwalk = "0.8.1"
miette = { version = "5.10.0", features = ["fancy"] }
futures = "0.3.28"
xmlparser = "0.13.5"


