[package]
name = "odoo-lsp-zed"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive", "serde_derive"] }
zed_extension_api = "0.6.0"

