name: test

on:
  push:
    branches: [main]
    paths:
      - "**/*.rs"
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-testing:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            coverage: yes
            rust: stable
          - runs-on: ubuntu-latest
            coverage: no
            rust: nightly
          - runs-on: macos-latest
            coverage: no
            rust: stable
          - runs-on: windows-latest
            coverage: no
            rust: stable
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
          cache-key: ${{ runner.os }}
          rustflags: ""

      - name: Create dummy tag
        run: git tag -f CI

      - name: cargo clippy
        if: matrix.rust == 'nightly'
        run: cargo clippy --all-features

      - uses: taiki-e/install-action@cargo-nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
        if: matrix.coverage == 'yes'

      - name: Run unit tests
        id: cargo-test
        if: matrix.coverage == 'no'
        continue-on-error: true
        run: cargo nextest run -p odoo-lsp -p odoo-lsp-tests --all-features --profile ci

      - name: Run unit tests (with coverage)
        id: cargo-testcov
        if: matrix.coverage == 'yes'
        continue-on-error: true
        shell: bash
        run: |
          set -euxo pipefail
          cargo llvm-cov clean --workspace -v
          cargo llvm-cov --codecov --output-path lcov.info nextest -p odoo-lsp -p odoo-lsp-tests --all-features --profile ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (${{ matrix.runs-on }}-${{ matrix.rust }})
          path: target/nextest/ci/junit.xml

      - name: Delete coverage artifacts
        if: steps.cargo-testcov.outcome != 'skipped'
        shell: bash
        run: |
          set -euxo pipefail
          source <(cargo llvm-cov show-env --export-prefix)
          cargo llvm-cov clean --workspace -v

      - name: Upload coverage report
        if: steps.cargo-testcov.outcome == 'success'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true

      - name: Fail or warn if unit tests failed
        if: steps.cargo-test.outcome == 'failure' || steps.cargo-testcov.outcome == 'failure'
        shell: bash
        run: |
          if [ "${{ matrix.rust }}" = "stable" ]; then
            exit 1
          else
            echo "::warning file=,title=Nightly unit tests failed::This is only informational and not a blocker."
          fi

  e2e-report-results:
    name: Report test results
    needs: e2e-testing
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/**/junit.xml
